preferred_syntax = :sass
http_path = '/'
css_dir = 'assets/css'
sass_dir = 'assets/sass'
images_dir = 'assets/img'
javascripts_dir = 'assets/js'
fonts_dir = 'assets/fonts'
relative_assets = true
line_comments = true
# output_style = :compressed