<?php
/**
 * PHP Array for English phrases
 */
array_push($phrases,
		'from behind',
		'dying',
		'die',
		'killing',
		'kill',
		'murder',
		'white children',
		'bottom inspector',
		'raping',
		'rapping',
		'rape',
		'stab',
		'pink balloon',
		'tear off',
		'poor excuse',
		'nail you',
		'hate',
		'finger you',
		'coming for you',
		'delete your account',
		'stupid bitch',
		'whitegenocide',
		'white genocide',
		'white power',
		'white powah',
		'white powa',
		'corpse',
		'electrocute',
		'choke',
		'in your house',
		'#gamergate',
		'gamergate'
);